### ISSUE TITLE
[Question] Thermal Expansion Integration

### ISSUE THREAD

**Issue by xlxAciDxlx** [MinecraftModDevelopmentMods/BaseMetals#261] opened 2018-01-15 13:02 UTC
Does the Thermal Expansion config option only register ore->ingot registries, or is it also supposed to register pulverizer recipes? I'm currently only getting ore->ingot recipes. Also, if it's only supposed to do ore->ingot, may I ask that ore->dust recipes be added? I tried to do it with Craft/MineTweaker, but no such luck (the recipes work, they just instantly process). Thanks :D

*Minecraft:* 1.12
*Forge:* 14.23.1.2589
*BaseMetals:* 2.5.0-beta3.51
*OreSpawn:* (not sure if relevant/needed) 3.2.1.109

**Comment by dshadowwolf** [comment] 2018-02-22 20:29
There are some known issues with the Thermal Expansion integration that have led to it not receiving the same attention as other integrations - more because the known issues seem to require specific sets of timing and certain things to happen that should not happen.

It is unclear what the root cause actually is. We will try to resolve this after some of the easier to locate and fix bugs are fixed.

**Comment by dshadowwolf** [comment] 2018-02-23 15:41
fixed in -dev

**Closed as completed** 2018-03-16 05:36 UTC
Labels: bug
