### ISSUE TITLE
Quartz block mining

### ISSUE THREAD

**Issue by jonevance** [MinecraftModDevelopmentMods/BaseMetals#420] opened 2019-02-12 13:09 UTC
I'm having the same issue as post number number 240 on Curseforge.  Hammering quartz blocks just makes them disappear.  In JEI it is showing three "recipes" for hammer / quartz block.  One is for the expected four quartz, one is for nine quartz dusts and the presumed problem recipe is the first one, which is for nothing.

**Comment by dshadowwolf** [comment] 2019-04-13 00:18
Not sure what the issue is here, possibly a bad item selection in the code. Unable to reproduce in current -dev - closing as resolved.

**Closed as completed by dshadowwolf** 2019-04-13 00:18 UTC
