### ISSUE TITLE
Mekanism Support not Working in Modern Metals

### ISSUE THREAD

**Issue by D3nnis3n** [MinecraftModDevelopmentMods/BaseMetals#184] opened 2017-09-21 15:46 UTC
Another Report, while i was thinking mekanism will work (because it works when the ore to use is from mekanism or a mod that has native Support with it), it seems there is no slurry and clean slurry for your metals, therefore it can't be dissoluted or washed. Also the purification in the chamber does not work, seems like the recipes are missing or something along that. 2.5.0-Beta2.8.

I suspect the complete implementation is still missing and my report is unneeded, but i wanted to post ist nevertheless as you posted mekanism was not tested yet in the CurseForge page.

**Comment by dshadowwolf** [comment] 2017-09-21 19:06
...fffff

Might have to shift around the Mek interface registration the same way I had to do for IC2, actually. Seems like we've got some issues with it on that side. I'll add this to the list and get back to you when a possible fix is ready.

**Comment by D3nnis3n** [comment] 2017-09-21 20:50
Take your Time. Just thought it would be good to Let my Mates test ans report the Outcome.

**Comment by dshadowwolf** [comment] 2017-09-21 21:41
and a good one!

Found that I don't have ore->crushed, but ore->clump, clump->dirty and dirty->clean works - going to try tier 3 next and then head for tier's 4&5 - just to confirm

**Comment by D3nnis3n** [comment] 2017-09-21 21:43
That sounds great! What about the Slurrys in the Washer and the Dissolution Chamber?

*Giving Coffee*

Gesendet von Mail für Windows 10

Von: dshadowwolf
Gesendet: Donnerstag, 21. September 2017 23:41
An: MinecraftModDevelopmentMods/BaseMetals
Cc: D3nnis3n; Author
Betreff: Re: [MinecraftModDevelopmentMods/BaseMetals] Mekanism Support notWorking (#184)

and a good one!
Found that I don't have ore->crushed, but ore->clump, clump->dirty and dirty->clean works - going to try tier 3 next and then head for tier's 4&5 - just to confirm

**Comment by dshadowwolf** [comment] 2017-09-21 22:00
Okay - have run the entire Tier 4 chain with Copper, Silver and Osmium from BaseMetals and it worked. Tried with Cold Iron and Adamantine and it doesn't work. So... We've got two of them, confirmed, as not fully integrating - not integrating at all, actually.

**Comment by D3nnis3n** [comment] 2017-09-21 22:02
Okay, well, i can’t exactly say what the Problem with us was as we got loads of mods that add e.g. copper. What about tin? Did this work at you?

Gesendet von Mail für Windows 10

Von: dshadowwolf
Gesendet: Freitag, 22. September 2017 00:00
An: MinecraftModDevelopmentMods/BaseMetals
Cc: D3nnis3n; Author
Betreff: Re: [MinecraftModDevelopmentMods/BaseMetals] Mekanism Support notWorking (#184)

Okay - have run the entire Tier 4 chain with Copper, Silver and Osmium from BaseMetals and it worked. Tried with Cold Iron and Adamantine and it doesn't work. So... We've got two of them, confirmed, as not fully integrating - not integrating at all, actually.

**Comment by dshadowwolf** [comment] 2017-09-21 22:09
Only able to reproduce with Adamantine and Cold Iron so far - I've run Silver and Copper through the entire chain.

I've got a -beta2.9 building now that includes quite a few fixes. It is what I've been testing and working on here and includes a *LOT* of work across the board.

**Comment by D3nnis3n** [comment] 2017-09-21 22:19
I’ll download it and look into it, my friends are not available until tomorrow. Thanks for your work! I’m so happy you are such a nice developer :D

**Comment by D3nnis3n** [comment] 2017-09-21 22:34
Just tested with Platinum (which should be a base metal, but modern metals also do not work) - does not work. Still seems like only ores work that are integrated by other mods. Maybe i'm just freaking dumb. (Silver and Copper are added by other mods in my instance)

**Comment by dshadowwolf** [comment] 2017-09-21 22:53
Eh... Let me try something - something similar to what I've done to get IC2 integration started on functioning  (I've got to complete the materials list and run-through, as well as add a few error checks, but the simple test in the code right now (integrating Adamantine) works)

**Comment by D3nnis3n** [comment] 2017-09-21 23:06
As ever take your time, i’m willing to test whenever you’re ready. Making Mod Packs takes so much time, developing so much more.

Gesendet von Mail für Windows 10

Von: dshadowwolf
Gesendet: Freitag, 22. September 2017 00:59
An: MinecraftModDevelopmentMods/BaseMetals
Cc: D3nnis3n; Author
Betreff: Re: [MinecraftModDevelopmentMods/BaseMetals] Mekanism Support notWorking (#184)

Eh... Let me try something - something similar to what I've done to get IC2 integration started on functioning (I've got to complete the materials list and run-through, as well as add a few error checks, but the simple test in the code right now (integrating Adamantine) works)

**Comment by dshadowwolf** [comment] 2017-09-21 23:11
That test works, somewhat, but leads to a crash... Lets see if its the "gas" for the (Dirty) Slurry (and yeah, the Slurries are gasses, according to Mek), the one for the "clean" Slurry or what...

**Comment by D3nnis3n** [comment] 2017-09-21 23:12
Yeh, that is something that i hate, too. Slurry as Gas *urgh* It’s not a gas. But it seems like you are near the solution :D

Gesendet von Mail für Windows 10

Von: dshadowwolf
Gesendet: Freitag, 22. September 2017 01:11
An: MinecraftModDevelopmentMods/BaseMetals
Cc: D3nnis3n; Author
Betreff: Re: [MinecraftModDevelopmentMods/BaseMetals] Mekanism Support notWorking (#184)

That test works, somewhat, but leads to a crash... Lets see if its the "gas" for the (Dirty) Slurry (and yeah, the Slurries are gasses, according to Mek), the one for the "clean" Slurry or what...

**Comment by dshadowwolf** [comment] 2017-09-21 23:32
And... Mekanism API needs more comments and docs - and it seems that Mek might not like it when the Gas is not created from a fluid and the given texture name doesn't map to an actual file... Forgot that we just recently started getting the Mek plugin actually functional and might not have the graphics avail - changing the setup to base from the materials fluid

**Comment by D3nnis3n** [comment] 2017-09-22 00:38
Working and a placeholder graphic is better than not working 😃
Mekanism is a great mod, even tough it has it’s oddities. It has so much senseful Content that works very well. I like it much and dropped IC2 for it.
I’m so happy BaseMetals decided to Support it. 5x Ores is really needed in my packs, as i distribute the ores near real world Distribution and some ores that are needed are very uncommon, while others that are not needed so much are pretty common.
But i like it to be more realistic :D

Gesendet von Mail für Windows 10

Von: dshadowwolf
Gesendet: Freitag, 22. September 2017 01:32
An: MinecraftModDevelopmentMods/BaseMetals
Cc: D3nnis3n; Author
Betreff: Re: [MinecraftModDevelopmentMods/BaseMetals] Mekanism Support notWorking (#184)

And... Mekanism API needs more comments and docs - and it seems that Mek might not like it when the Gas is not created from a fluid and the given texture name doesn't map to an actual file... Forgot that we just recently started getting the Mek plugin actually functional and might not have the graphics avail - changing the setup to base from the materials fluid

**Comment by dshadowwolf** [comment] 2017-09-22 01:00
Well... no longer crashing when it tries to pump the dirty into the chemical washer, but...

Okay, seems that we might need to create a fluid with a variant name to use as the base of the "clean" slurry...

**Comment by D3nnis3n** [comment] 2017-09-22 01:12
Seems like it’s working out well for you at the Moment. For me it’s time to go to bed, 3:12 am here. Good Night! :D

Gesendet von Mail für Windows 10

Von: dshadowwolf
Gesendet: Freitag, 22. September 2017 03:00
An: MinecraftModDevelopmentMods/BaseMetals
Cc: D3nnis3n; Author
Betreff: Re: [MinecraftModDevelopmentMods/BaseMetals] Mekanism Support notWorking (#184)

Well... no longer crashing when it tries to pump the dirty into the chemical washer, but...
Okay, seems that we might need to create a fluid with a variant name to use as the base of the "clean" slurry...

**Comment by dshadowwolf** [comment] 2017-09-22 04:31
and... Just PR'd (#188) the fixes for this and now I'll be going over to poke at Modern Metals.

Closing this as testing shows none of the crashes that early work on this fix exhibited and all 4 tiers of Mek ore processing work.

**Comment by dshadowwolf** [comment] 2017-09-22 04:32
bah, lets let it auto-close on the PR being merged

**Comment by D3nnis3n** [comment] 2017-09-22 05:59
Dissolution Chamber, Purificator and Washing working with Base Metals on Mekanism. Great Job! :) Hope i was not too enerving, but a bit helpful.

//EDIT: Auto-Close didn't seem to work. I changed the title to in modern metals, if that's okay - as that's left of the issue.

**Comment by dshadowwolf** [comment] 2017-09-22 06:13
Yeah. I actually know exactly what the issue is and how to fix it. Modern Metals will be getting that fixes after I get sleep. (got stopped by answering some questions and looking into strange behavior in BaseMetals that was reported by a Mekanism dev who is, himself, looking into some strange behavior in Mekanism that I found while working on the fix that is currently in place)

**Closed as completed by dshadowwolf** 2017-09-22 06:13 UTC

**Comment by D3nnis3n** [comment] 2017-09-22 06:15
Seems great. Any Chance that you will have both integrations working this Weekend? We got the most players to test then :D 

Now get some sleep, i only had four hours, doesn't feel good. Thanks for all your hard work today, you managed a lot of fixes :O Yeh, you answered a lot of my issues today, too. *g*

**Comment by dshadowwolf** [comment] 2017-09-22 16:19
And the Mek dev got back to me after I woke up with a suggestion for a proper fix. No more special sub-class and no more potential issues with the slurries being able to be condensed :)

**Comment by D3nnis3n** [comment] 2017-09-22 18:06
Cool. Does this fix it in ModernMetals, too or is this for BaseMetals only at the Moment?

**Comment by dshadowwolf** [comment] 2017-09-22 19:11
And... needs a bit of work - I thought handing the materials in would be enough, but apparently it isn't... There is no multiplication happening right now. Found the first place that has to change :)

**Comment by D3nnis3n** [comment] 2017-09-22 19:14
You mean too less liquid or what? I get three clumps out, that seems like multiplicating. To be honest, i'm more Building the pack than playing it :D

**Comment by dshadowwolf** [comment] 2017-09-22 19:41
Somewhat... Tier 4 was not multiplying at all - it was straight 1 ore is 1 crystal - turned out to be a value error in the code. I had a thinko where I'd placeholdered a value (amount of millibuckets per recipe) at 1000 and for the 5x of T4 it needs to be 200mB

PR #191 fixes that as well as fleshing out the IC2 integration and implementing everything except the IC2 Forge Hammer recipes.

**Comment by D3nnis3n** [comment] 2017-09-22 20:38
Haha, great work, again. Pressing my fingers for ModernMetals Integrations 😊

Is there a way to buy you a coffee?

**Comment by dshadowwolf** [comment] 2017-09-22 20:47
Modern Metals is actually queued - just waiting for me to get the recipe fixes out of the way

**Comment by D3nnis3n** [comment] 2017-09-22 20:50
Great. I applied Base Metals 2.5.0-Beta2.12 on our production Server and exchanged the thermalexpansion items to them, let's see what happens. That will unify the first metals - happy. If i get any Problems or recipe Bugs i'll Report to you.

**Comment by dshadowwolf** [comment] 2017-09-23 02:26
TE integration is partially automatic at this point - we've had a *LOT* of issues with it in the past, so I'm going to see if that's solved now with the change in how reg is done and when OreDict is supposed to be done and all that

**Comment by dshadowwolf** [comment] 2017-09-23 04:25
More fixes and cleanups with #192 (and MMe PR number 70) - should have all this working correctly when merged

**Comment by D3nnis3n** [comment] 2017-09-23 12:13
As for modern metals i could not test, as it crashes but for Base Metals it seems fine. Only Thing missing is the language files for Clean Slurry and Slurry. Great!

**Comment by dshadowwolf** [comment] 2017-09-23 18:12
...I think thar I'm going to need that crash log - I get no crashes here. (And are you using the latest build from the maven ?)

**Comment by D3nnis3n** [comment] 2017-09-23 18:38
Yes, i ever write my Version to it so you don't Need to ask. There is an issue with the Crash. I post my complete Crash log there. It's 2.43 Modern Metals and 2.13 Base Metals.

https://github.com/MinecraftModDevelopmentMods/BaseMetals/issues/193
