### ISSUE TITLE
[1.12.2] Server NumberFormatException

### ISSUE THREAD

**Issue by Secretname2009** [MinecraftModDevelopmentMods/BaseMetals#469] opened 2020-07-04 15:04 UTC
Im trying to create a MC Forge Server but after a bit of startup it crashes with this error log.
This happends even after disabling the crossbow and bolts.
[crash-2020-07-04_16.51.19-server.txt](https://github.com/MinecraftModDevelopmentMods/BaseMetals/files/4873038/crash-2020-07-04_16.51.19-server.txt)

Current Versions
Minecraft 1.12.2
Forge 14.23.5.2854
MMDLib 1.0.0 rc2.36
Basemetals 2.5.0 rc2.332

**Comment by dshadowwolf** [comment] 2020-07-04 16:07
Duplicate of #407 - closing.

**Closed as completed by dshadowwolf** 2020-07-04 16:07 UTC
