### ISSUE TITLE
Blacksmith villager issues

### ISSUE THREAD

**Issue by CatastropheBlack** [MinecraftModDevelopmentMods/BaseMetals#244] opened 2017-12-24 22:17 UTC
Blacksmith villagers are causing errors and they have empty trades when BaseMetals is loaded.  OreSpawn alone does not cause these errors with villagers, and errors are limited to blacksmith villagers.

MC v1.12.2
Forge v14.23.1.2555
MMD OreSpawn v3.2.0.95
BaseMetals v2.5.0-beta3.51

```
[Server thread/ERROR] [FML]: An Entity type net.minecraft.entity.passive.EntityVillager has thrown an exception trying to write state. It will not persist. Report this to the mod author
net.minecraft.util.ReportedException: Saving entity NBT
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1768) ~[vg.class:?]
	at net.minecraft.entity.Entity.func_70039_c(Entity.java:1650) ~[vg.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:359) [aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:171) [aye.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:230) [on.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1006) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71267_a(IntegratedServer.java:252) [chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:170) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at net.minecraft.village.MerchantRecipe.func_77395_g(SourceFile:132) ~[amg.class:?]
	at net.minecraft.village.MerchantRecipeList.func_77202_a(SourceFile:133) ~[amh.class:?]
	at net.minecraft.entity.passive.EntityVillager.func_70014_b(EntityVillager.java:338) ~[ady.class:?]
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1739) ~[vg.class:?]
	... 11 more
```

```
[Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at net.minecraft.village.MerchantRecipeList.func_151391_a(SourceFile:83) ~[amh.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_180472_a(EntityPlayerMP.java:929) ~[oq.class:?]
	at net.minecraft.entity.passive.EntityVillager.func_184645_a(EntityVillager.java:273) ~[ady.class:?]
	at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1227) ~[vq.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1199) ~[aed.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1071) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) ~[li.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) ~[li.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```

![2017-12-24_15 05 48](https://user-images.githubusercontent.com/33291018/34329417-a5040fd6-e8bc-11e7-9483-66d6c75bf72e.png)

**Comment by dshadowwolf** [comment] 2017-12-25 00:33
Thank you for this report and the work in localizing it. I'd seen it before but not known if it was actually BaseMetals or if it was an inter-mod issue and did not have the time to examine more closely.

Sadly this doesn't say what the error is, but as the last of the remaining code from the original pre-1.10 versions of BaseMetals is actually the code dealing with the trades that get added to the Blacksmith and other villagers, there is a good chance that it is somewhere in there.

@cyanobacterium was a genius with writing compact, functional code but it tends to rely heavily on the way specific versions act instead of being generic enough to withstand some changes to Forge/Vanilla and nobody on the team, right now, fully understands everything that his code does. (yes, sad, but when dealing with genius, this is often the case)

Hopefully we'll have figured this out by the time 2.5.0 reaches a final release state.

**Comment by dshadowwolf** [comment] 2017-12-25 21:30
@jriwanek has found the root cause(s) of this bug and it is reported as having been fixed in development versions. This issue will be closed when the next -beta is released to Curse with this issue resolved.

**Comment by CatastropheBlack** [comment] 2017-12-26 02:12
Awesome!  Blacksmiths are no longer erroring, and trades are available.  However, now blacksmiths start with all trades open (and it's a long list of trades, around 200).  Also, there are some strange _emeralds -> emeralds_ and _emeralds -> diamonds_ trades which could be used to get infinite emeralds & diamonds.  I suspect this has something to do with trades being created for 12 of each tool making material (mostly ingots, but also diamonds and emeralds).

![2017-12-25_19 04 08](https://user-images.githubusercontent.com/33291018/34344793-af74761e-e9a6-11e7-9419-3ef14e53093b.png)

![2017-12-25_19 03 50](https://user-images.githubusercontent.com/33291018/34344794-b136ee82-e9a6-11e7-9085-c2837c6f4a59.png)

Thanks for your work on this!  Hope you all had a happy holiday!

**Comment by jriwanek** [comment] 2018-01-03 04:51
Dupe bug fixed

**Comment by dshadowwolf** [comment] 2018-01-05 22:45
Fixed in dev, will be in next release - closing

**Closed as completed by dshadowwolf** 2018-01-05 22:45 UTC
Labels: Base Metals
