### ISSUE TITLE
Adamantite Mining Speed = 0

### ISSUE THREAD

**Issue by D3nnis3n** [MinecraftModDevelopmentMods/BaseMetals#183] opened 2017-09-21 15:11 UTC
Just reported by one of my test-Players that adamant has a mining Speed of 0 whick makes it unusable to mine any Stone or ores :D Affects 2.5.0-Beta2.8

**Comment by dshadowwolf** [comment] 2017-09-21 19:08
...okay, this ties into a lot of other stuff thats been going on and needs looked into

**Comment by dshadowwolf** [comment] 2017-09-23 04:25
If the plugins are working and no more recipes bugs are found, I can look into this (finally)

**Comment by dshadowwolf** [comment] 2017-09-23 04:38
And... is this a Tinkers' Tool or vanilla style ?

Need to know so I can narrow down where to look

**Comment by dshadowwolf** [comment] 2017-09-23 04:44
Nevermind, testing shows its Tinkers', which means I get to dive into some tricky code

**Comment by dshadowwolf** [comment] 2017-09-23 05:02
...how was this not reported in the past? This has been a bug since @jriwanek wrote the first version of the Tinkers' Integration - all MMD Materials have a "Magic Affinity" stat that gets used in a number of places - @jriwanek used it, herself, as part of a calc in the original code to figure the mining speed of a material based off it. Adamantine has a Magic Affinity of zero.

**Comment by D3nnis3n** [comment] 2017-09-23 11:45
As you already guessed, it was a tinkers tool. I really don't know why noone reported this earlier, but for us it was pretty easy - most of us are D&D fans and we thought Adamant to be one of the best materials, especially for durability *g* But it cleary wasn't without a mining Speed 🗡 

As far as Magic affinity of adamantine goes, i'm not sure how enchantable it should be, but because of it's hardness it should sureley be able to be a good mining tool, even if it is not so enchantable.

**Comment by dshadowwolf** [comment] 2017-09-23 18:40
Yes - me and @jriwanek have been discussing this as making vanilla-style tools with it produces some decent tools.

**Comment by dshadowwolf** [comment] 2017-09-23 21:48
And... @D3nnis3n - https://discord.gg/2TSs7p  -- this will expire in ~24 hours, but that's the MMD Public Discord - come and join the community.  (I'm there and somewhat active most days)

**Comment by dshadowwolf** [comment] 2017-09-23 23:06
Fix for this being committed and pushed now. Any existing adamantine/adamantite tools will need to be replaced as tools carry their stats in their NBT after creation.

**Closed as completed** 2017-09-23 23:42 UTC

**Comment by D3nnis3n** [comment] 2017-09-24 02:32
Yap, works. As for discord i'll see. I haven't gotten discord yet. We still (and will further) use teamspeak, as we find that A LOT better and don't like discord much ... (especially because they are Advertising against mumble and teamspeak while they're not nearly able to really replace them if you Need configuring of your Server ... - permission flexibility = Zero)

**Comment by dshadowwolf** [comment] 2017-09-24 03:04
well... Discord is actually pretty close to a replacement for Skype these days

**Comment by D3nnis3n** [comment] 2017-09-24 03:20
Oh, i never used Skype. As we are a clan since 2005, we only used teamspeak. It's time to sleep for me anyways (5 am) - maybe we hear from each other tomorrow.

**Comment by dshadowwolf** [comment] 2017-09-24 03:23
Does Video, Sound and Text

Has Servers ("Guilds" in the documentation and API) and "Channels" for things, recently introduced the ability of servers to categorize the channels. Has a pretty complex system of permissions and server-wide user-groups.

It's actually quite good, despite the company being a touch on the douche-bag side.

**Comment by dshadowwolf** [comment] 2017-09-24 04:23
Video (they've shown this, but I don't know if its available), Text and Voice chat - Discord has this.

Servers for different groups? Again, this is there.

Channels for different topics ? Available.

Decent permissions system ? It's there.

Game relay, IRC relay, etc... It's possible, just needs the code on the other end and some setup work.

Discord is, aside from having some douche-baggy moments in advertising and such, quite complete and a usually decent system. Even has a full in-browser client that, sadly, has some issues with the video and voice parts.

**Comment by D3nnis3n** [comment] 2017-09-24 04:27
The permission system of discord is decent? You never saw teamspeaks permission system, did you? Discord’s is a pile of shit against that. And we make heavy use of this extensive system. People might think it’s overly complex – no it’s not. You just can do about everything you want. But you don’t have to.

Other than that, you are right – but TeamSpeak has all this for ages and i have full control over it. It’s just not my software and will never be. I might test it out tomorrow again just for your channel, but i will never use it extensively – it’s just not good enough for that in the use cases we use teamspeak for.

And as i said, we never did use skype – so there is no Need to replace this for us :D

Gesendet von Mail für Windows 10

Von: dshadowwolf
Gesendet: Sonntag, 24. September 2017 06:23
An: MinecraftModDevelopmentMods/BaseMetals
Cc: D3nnis3n; Mention
Betreff: Re: [MinecraftModDevelopmentMods/BaseMetals] Adamantite Mining Speed= 0 (#183)

Video (they've shown this, but I don't know if its available), Text and Voice chat - Discord has this.
Servers for different groups? Again, this is there.
Channels for different topics ? Available.
Decent permissions system ? It's there.
Game relay, IRC relay, etc... It's possible, just needs the code on the other end and some setup work.
Discord is, aside from having some douche-baggy moments in advertising and such, quite complete and a usually decent system. Even has a full in-browser client that, sadly, has some issues with the video and voice parts.

**Comment by dshadowwolf** [comment] 2017-09-24 04:47
Actually, I missed the TeamSpeak era entirely and the only issues I've found with the Discord permission system is that some things seem to override everything for no reason. The Discord the invite is for is a quite large one with some well-known folks - cover1624 (part of TeamCoFH and current maintainer of the Code Chicken stuff), Eladkay, Gegy, Corosus, CovertJaguar, McJty, Ellpeck... a lot of modders and some Streamers/YouTubers (Darkosto, for one) and lots of others. I'm consistently stunned by people that pop up here. If they've got an actual, defined role then we've confirmed the identity. (Save Ellpeck, who we know is Ellpeck, but who has refused to ask for the role or jump through the hoops we require for proving identity)

**Comment by D3nnis3n** [comment] 2017-09-24 13:06
Haha, well, that intimidates me a bit. I know quite some of these names. Especially CovertJaguar. Which i forecefully Need to restrain myself from asking if he will update to 1.12. RailCraft is sooo nice.

Well, i did register now but i'm smited of the discord. I don't really know what to do where. 🗡 

You missed the TeamSpeak Era? I'm 24. How could anyone miss the teamspeak era? :O

**Comment by dshadowwolf** [comment] 2017-09-24 14:03
I'll be 40 in about half a year. I missed the "Teamspeak Era" because, at the time, I wasn't doing voice chat for anything other than work - and that was skype, Everything else was email, IM of some sort, or IRC

and... Pinged you on Discord to give you a welcome and let you know I saw your name in the list :)

**Comment by D3nnis3n** [comment] 2017-09-24 16:31
Well, i look into it further Today. For now this is a Bad day. 13,5% nazis
just got elected in our Federal German elections.

Am 24.09.2017 16:03 schrieb "dshadowwolf" <notifications@github.com>:

**Comment by dshadowwolf** [comment] 2017-09-24 16:44
That worries me more than I was when Trump won our Presidential Election.

**Comment by D3nnis3n** [comment] 2017-09-24 16:51
Just ... :(
