### ISSUE TITLE
Null string not allowed - base metals 1.12.2 - 2.5.0 beta7.311

### ISSUE THREAD

**Issue by Andrea-98** [MinecraftModDevelopmentMods/BaseMetals#419] opened 2019-02-10 13:07 UTC
https://paste.dimdev.org/meguqewela.mccrash

**Comment by dshadowwolf** [comment] 2019-02-10 19:43
...Something is interfering with fluid registration code - I have been poking at this and trying to figure out how it triggers, since there are checks in the code to make sure things like this do not occur, and cannot get it to happen.

Is there a pack and custom configs you are using ?

**Comment by dshadowwolf** [comment] 2019-02-10 19:49
To be more specific - this is being triggered by a request for a filled bucket of Mercury so a recipe can be manually registered, in code. Around this are checks to make sure this is possible to do. The crash itself happens inside Forge code when it tries to actually create the bucket and is given a null-string for the fluid name. That code, in Forge, has guards around it to make sure the fluid exists and was properly registered.

At this point my only guess as to what is happening is that something is monkeying with the FLuid Registry and causing a mismatch between data sets somewhere.

**Comment by Andrea-98** [comment] 2019-02-11 05:03
I'm using the basic auto config generated, there is no custom script where you edit or add recipe. when I insert the base metal mods modern metal end metal dense metal base material and MMD ore spawn generates that erorr

**Comment by dshadowwolf** [comment] 2019-02-11 05:47
Okay - I've not been able to reproduce with just the *Metals in testing, which is why I asked. Guess I'll have to see if adding another mod from the set listed in the crash reproduces

**Comment by Andrea-98** [comment] 2019-02-11 07:32
I use additional mods that add materials, moreover its modalities are integrated automatically in other mods.

**Comment by dshadowwolf** [comment] 2019-02-11 08:35
And something is causing a request of the fluid registry for Mercury to return a fluid will a NULL name - I think the fix here would be for us to add our own tracking of our fluids instead of just turning to the Fluid Registry for it all, but...

**Comment by macqo004** [comment] 2019-03-10 09:12
any way to fix it? Even temp fix is fine

**Comment by dshadowwolf** [comment] 2019-03-10 13:41
Unable to reproduce, but have a new release being worked on that may resolve this

**Comment by macqo004** [comment] 2019-03-10 14:55
Removing planarartifice-0.12.2/fluid+++1.9-1.12.2 fixed it for me

**Comment by dshadowwolf** [comment] 2019-04-13 00:07
Okay, flagging this as a bad cross-mod - it might be that fluid++ or planarartifice is using ASM or similar and causing a negative interaction in some manner. Closing as it seems to be triggered by another mod doing something that has a bad corner-case.

**Closed as completed by dshadowwolf** 2019-04-13 00:07 UTC
