### ISSUE TITLE
Forge 14.23.5.2768, server, crash

### ISSUE THREAD

**Issue by gtokarz** [MinecraftModDevelopmentMods/BaseMetals#378] opened 2018-10-06 08:51 UTC
I am trying to setup local minecraft server with only OreSpawn and BaseMetals as a mods, having crash at each attempt
[latest.log](https://github.com/MinecraftModDevelopmentMods/BaseMetals/files/2452854/latest.log)

**Comment by dshadowwolf** [comment] 2018-10-06 11:25
BaseMetals crash is known and is caused by a bit of stupidity on my part - I believe @jriwanek has a fix for this in -dev already.

**Comment by jriwanek** [comment] 2018-10-19 11:54
Fixed in dev

**Comment by dshadowwolf** [comment] 2019-05-17 21:32
fixed in -dev

**Closed as completed by dshadowwolf** 2019-05-17 21:32 UTC
Labels: bug
