### ISSUE TITLE
[1.12.2][CrashOnLoading]

### ISSUE THREAD

**Issue by drakray** [MinecraftModDevelopmentMods/BaseMetals#265] opened 2018-01-31 01:02 UTC
https://pastebin.com/nKigytfj

`Caused by: java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =class cofh.thermalexpansion.util.managers.machine.SmelterManager$ComparableItemStackSmelter id= 639059686 hashCode= 666566656 toString= cofh.thermalexpansion.util.managers.machine.SmelterManager$ComparableItemStackSmelter@639059686{m:0, i:com.mcmoddev.lib.item.ItemMMDPowder@396728028, v:10171}; object #2 =class cofh.thermalexpansion.util.managers.machine.SmelterManager$ComparableItemStackSmelter id= 2100894975 hashCode= 1191 toString= cofh.thermalexpansion.util.managers.machine.SmelterManager$ComparableItemStackSmelter@2100894975{m:0, i:com.mcmoddev.lib.item.ItemMMDPowder@396728028, v:10171}`

Relevant part is com.mcmoddev.lib.item.ItemMMDPowder

Was posted on Thermal some time ago, they said it's on your side, something about late oreDict registration

**Comment by dshadowwolf** [comment] 2018-01-31 02:09
Yeah, but they are wrong about the cause. We've not been able to conclusively find the cause and one of the potential causes is something that we can't actually figure out the **HOW** to it happening. (besides, that was some ancient 1.10.2 code) - but "late oreDict registration" is idiotic as we've always done the oreDict at the correct times (either in preInit for MC < 1.12 or alongside the Item registration in the "RegistryEvent.Register<Item>" event handler (MC 1.12 or later))

Seriously, though... its almost like there is some sort of backlash happening, where one of the Items or Blocks in a recipe turns out to be null even though it shouldn't be...

Now, so we can replicate it... Is this happening in a published pack or modification of such and what are the versions of the various mods ?

PS: Note that, in this instance, Lemming spouted off some bullshit and pointed fingers without ever, actually, looking at the code or even contacting us. It was just "It isn't Thermal! Its the other guys - they're doing it wrong!"... I don't know him and have never even spoken to him other than a rebuttal on a Reddit thread when this issue first popped up, but the finger-pointing has got to stop. The professional thing would have been to contact us and let us know about the issue instead of yelling and pointing fingers.

**Comment by drakray** [comment] 2018-01-31 02:17
I'm sorry to hear that, I just tried to find some info about this, and all I could find was that old thing so :/

MC 1.12.2
Forge 2607
[Java Arguments](https://github.com/MinecraftModDevelopmentMods/BaseMetals/files/1680150/jvm.arg.txt)
[Private ModPack](https://www.dropbox.com/s/zji39vggq54e7mv/1122M.zip?dl=0), with log and crash report
I really don't know why it's happening though, as I played with it and it worked, I updated some mod and it crashed, then worked, and now won't :S

**Comment by dshadowwolf** [comment] 2018-01-31 02:42
Hrm... This looks, again, like the old issue from 1.10.2 where adding just one mod that changed the load-timing of BaseMetals or ModernMetals caused the issue to not occur. Seriously... this is looking more and more like that and it shouldn't happen - the last time it was "The item exists but the 'get the item instance from our internal registry to setup the recipe' is returning NULL instead of the Item"... Still have no idea how that can be happening :(

**Comment by dshadowwolf** [comment] 2018-01-31 02:45
I'm actually wondering if we should stop registering things with the Thermal machines that they might pick up when importing Vanilla recipes - that actually seems to be part of what triggers this.

**Comment by drakray** [comment] 2018-01-31 02:50
If it can help, I started to get this after adding SmoothWater and updating PlusTiC to 6.3.5.0 (I since then when to 6.3.6.1, and updated LostCities, SignPost and LibrarianLib to latest)

That could help, I use UniDict anyway, and Chisel, so going from one Bronze to another is easy, if needed

**Comment by dshadowwolf** [comment] 2018-01-31 03:37
...PlusTiC has non-compats with ModernMetals Tinkers' integration...

**Comment by drakray** [comment] 2018-01-31 03:40
But it was working fine on Forge 2604 with PlusTiC 6.3.4.0 :/ (maybe because of Unidict?)

**Comment by drakray** [comment] 2018-01-31 04:00
Ok, just tried, and with the same pack, I can load without PlusTiC :S
I guess I'll make without for the time being. but that sure is some weird cross-mod interaction, as it was working before

**Comment by dshadowwolf** [comment] 2018-02-01 02:51
I'm actually wondering if we should stop registering things with the Thermal machines that they might pick up when importing Vanilla recipes - that actually seems to be part of what triggers this.

And I wasn't saying PlusTiC was causing this - I think I actually got rid of 99% of the \*Metals non-compat issues with PlusTiC but a number of mods that integrate with TiC will do things like, say, register a metal and expect it to just happen, even though it will cause a crash if another mod registered the same metal before.

(see Moar Tinkers and Modern Metals argue over Platinum, for instance)

On the other hand... this is definitively related to the timing-related bug that seems to make it so "add this to a Map<>", "is this in the Map<>" and "get this from the Map<>" can actually return contradictory values - such as "yes, I've added it", "yes, I have that" and "here is a NULL"... We've were unable to track it down, conclusively, because it makes no sense and seems to violate some Java guarantees...

**Comment by drakray** [comment] 2018-02-01 02:56
Well that sure is a very bad problem to try to debug lol
If you want I can try anything you throw at me, though you have my buggy pack so you could try the not-registering thing.
All I know for now is that removing PlusTiC from my pack "fixed" the problem, for now anyway, and I started to get it when updating, so it *might* be a culprit at some point(though I do have a bunch of mods that add metals in this pack)

**Comment by jriwanek** [comment] 2018-02-08 06:42
You can find early builds on the maven: https://maven.mcmoddev.com/

**Comment by drakray** [comment] 2018-02-08 18:19
Crash after updating just Base Metals to 4.134 https://pastebin.com/4d0MLvvr
Then crash after updating Modern Metals to 4.84(and End/Nether/Minerals/Orespawn too, from maven) https://pastebin.com/NxvP3ATF
With PlusTiC

EDIT: without PlusTiC too https://pastebin.com/Mm67ySKq

**Comment by drakray** [comment] 2018-02-08 18:44
Setting mekanism_integration=false in BaseMetals.cfg get the same crash, with or without PlusTiC

EDIT: adding Mekanism to the pack change nothing https://pastebin.com/iSFKL1TY

**Comment by drakray** [comment] 2018-02-10 05:51
Removed Mekanism, kept PlusTiC, updated to BaseMetals-1.12-2.5.0-beta4.136
New crash `(BaseMinerals)Caused by: java.lang.NoSuchFieldError: emptyMaterial` https://pastebin.com/mbUTQPr0

**Comment by jriwanek** [comment] 2018-02-10 09:55
Try baseminerals 1.12 build 23

I'll be working on ModernMetals, NetherMetals and End Metals tomorrow.

**Comment by drakray** [comment] 2018-02-10 15:06
with minerals 23, https://pastebin.com/Ta3g13kG

**Comment by drakray** [comment] 2018-02-11 23:47
seems to be working with today's build :D

**Comment by jriwanek** [comment] 2018-02-12 10:42
You're welcome. (:

**Comment by drakray** [comment] 2018-02-12 14:44
Just a heads up, I tried to add Mineralogy in my pack, and got the same crash as post 1, removed, no crash (I know it's not out, but I thought, why not try it anyway)

**Comment by SkyBlade1978** [comment] 2018-02-12 16:24
Thanks @drakray , although it's not 'out' yet the current build of mineralogy shouldn't be causing any crashes, the only issue I'm solving at the moment before a release is making it so you can double slab the slabs, so certainly if it's causing a crash we need to fix it (if possible).

Could I get you to post the crash report on the Mineralogy issues board with some info on how to reproduce, and aldo a crash log and we can try to fix it..

**Comment by dshadowwolf** [comment] 2018-02-22 20:27
@drakray new builds of all of *Metals should be on the Maven which should fix the later crash issues you noted. Those are caused by API changes in the -beta4 series where we cleaned up a lot of legacy stuff (we had a lot of things hanging around from really early in development of 2.5) and the mods getting out of sync as to the API.

**Comment by drakray** [comment] 2018-02-22 20:41
Using
```
AdditionalLootTables-1.12-2.0.3.37
OreSpawn-1.12-3.2.2.114
BaseMetals-1.12-2.5.0-beta4.155
BaseMinerals-1.12-2.5.0-beta4.27
ModernMetals-1.12-2.5.0-beta4.95
NetherMetals-1.12-1.2.0-beta2.35
EndMetals-1.12-1.2.0-beta2.24
```
everything work! :D 

but Bucket(.4&.11) crash(reported)
Trying adding Mineralogy right now

EDIT: Mineralogy 3.3.0.13 working! (but with some weirdness, like recipe showing weirdly in JEI)

**Comment by jriwanek** [comment] 2018-02-24 16:25
Okay, please report the mineralogy issue on it's own tracker, (Skyblade is currently handling that one), and we'll have a looksee about getting buckets updated too.

**Comment by dshadowwolf** [comment] 2018-02-24 17:45
Buckets has a fix in -dev

**Comment by jriwanek** [comment] 2018-03-16 05:36
closing as author says it's all working and we're on beta 5 now

**Closed as completed by jriwanek** 2018-03-16 05:36 UTC
