### ISSUE TITLE
BaseMetals_1.10.2-2.4.0.11 NoSuchMethodError: cyano.basemetals.BaseMetals.serverPreInit on client

### ISSUE THREAD

**Issue by sandalle** [MinecraftModDevelopmentMods/BaseMetals#160] opened 2017-07-23 05:03 UTC
BaseMetals_1.10.2-2.4.0.11 gives error "NoSuchMethodError: cyano.basemetals.BaseMetals.serverPreInit" on my client, but server loads fine.

crash-report: [crash-2017-07-22_22.01.07-client.txt](https://github.com/MinecraftModDevelopmentMods/BaseMetals/files/1167866/crash-2017-07-22_22.01.07-client.txt)

**Comment by dshadowwolf** [comment] 2017-07-23 15:37
Odd... we are slowly phasing out the 2.4 series from support, but this error should not be occurring - I have, in fact, run 2.4 on both client and server. This will be looked into.

**Comment by sandalle** [comment] 2017-07-23 15:50
Yeah, some update somewhere (mods like FoamFix or Forge itself) broke it, as I didn't have this error months ago when I last played the [NST Unofficial modpack](https://minecraft.curseforge.com/projects/nst-unofficial-frostburn).

**Comment by dshadowwolf** [comment] 2017-07-23 16:33
I doubt FoamFix - I know Asie and that code monkeys about in Forge internals to de-dupe models and some other (mostly) static data. However... the fact remains that part of the package is disappearing and I'm left wondering if we might have a stray annotation or similar in 2.4

**Comment by dshadowwolf** [comment] 2017-07-23 16:40
and... odd - That specific error would indicate that:
```java
                if(event.getSide() == Side.SERVER){
                        serverPreInit(event);
                }
```
Was running on the client, as 'serverPreInit' itself is:
```java
        @SideOnly(Side.SERVER)
        private void serverPreInit(FMLPreInitializationEvent event){
                // server-only code
        }
```

This says, to me, that Forge is likely to blame. The major issue, then, is that the 2.5 series - which cleans up a lot of the code, makes it more modular and much more robust - is not, yet, available for 1.10 (and is only early beta for 1.11)

I think I might have to set aside the work I've been doing on OreSpawn and try to backport both OreSpawn 3 and BaseMetals 2.5

**Comment by jriwanek** [comment] 2018-01-02 23:02
Have been unable to reproduce, development is happening now on 2.5.x and later so closing

**Closed as completed by jriwanek** 2018-01-02 23:02 UTC
Labels: Base Metals

**Comment by sandalle** [comment] 2018-01-27 01:08
I cannot reproduce this anymore either after deleting everything, re-installing [NST Frostburn (MC 1.10.2) modpack from Curse/Twitch](https://minecraft.curseforge.com/projects/nst-unofficial-frostburn), and then applying all updates to mods, including Forge Mod Loader to 1.10.2-12.18.3.2511.
