### ISSUE TITLE
No XP from smelting

### ISSUE THREAD

**Issue by Ivybug** [MinecraftModDevelopmentMods/BaseMetals#168] opened 2017-08-31 00:23 UTC
Playing with base metals for 1.11.2 and not getting any EX when smelting any metals or powders, including gold and iron.

**Comment by dshadowwolf** [comment] 2017-08-31 14:42
...okay, this should not happen - means that there might be a major difference in the 1.11 vanilla code surrounding the furnace - will look soon

**Comment by dshadowwolf** [comment] 2017-08-31 16:04
Alright... looks like we've got something odd going on - ores, blends and powders are registered for the configurable "ore smelting experience".For all *metals materials this is equal to an internal stat that also guides how "magical" the material is. So Star-Steel has the potential to give more XP than Copper, etc...

There might be an issue somewhere else in the code with how this is actually setup and working, so please be patient and I'll keep looking through the code - and maybe making some test builds with lots of debugging information - to see if I can figure out where this is going wrong.

**Comment by Ivybug** [comment] 2017-08-31 18:21
Just an update, I was incorrect about the gold, I am getting XP from that but not from iron or anything else I mentioned. If that helps you narrow down the problem.

**Comment by dshadowwolf** [comment] 2017-09-05 20:09
The actual code scales the XP based on the internal "how magical is it" value - Gold, Diamond and some other vanilla materials will give at least 1XP based on that scaling and it seems similar for most materials in *Metals - Aquarium, Electrum, Star-Steel and Platinum should give at least 1XP.

All the rest fall between 0 and 1 as floating-point values and that means that you'd need to smelt multiple at once to get the XP. The logic and code in Forge and Vanilla that back this has not changed on this for a long time - it does change heading into 1.12 thanks to the major internals changes (such as the json recipes) that come in there.

I've been unable to find an actual cause as yet, but it looks like it could just be that the system has most materials giving less than 1XP per smelt. The test you'd need to do is check to see if Star-Steel or Aquarium (this is an alloy, so from a blend, not an ore) give you any XP.

**Comment by Ivybug** [comment] 2017-09-05 23:26
I tested all the ores with a full block of 64 being smelted. I DID get Xp from the following: Liquid Mercury, Copper (even though in the past I didn't seem to get any), Platinum, and Rutile. I DID NOT get any from these: Gold (even though I thought I had in the past), Tin, Silver, Zinc, Lead, Nickle, Aquarium, Adimantium, Antimony, Bismuth, Star-Steel, Cold Iron, Iron, Iridium, Chromium, Cadmium, Aluminum, Plutonium, Tantalum, Magnesium, Manganese, Osmium, Uranium, Tungston.
I will give the blends a try next.

**Comment by dshadowwolf** [comment] 2017-09-05 23:30
Aquarium should give XP on smelt - it has a value up there above Copper (Copper is ~0.4xp per, Aquarium should be around 1.5XP per) - so... Looks like I'll need to do some deeper testing, as it seems that the code is claiming to work one way, but things seem to be working differently

**Comment by Ivybug** [comment] 2017-09-06 00:16
Tested all the blends - none give XP. On powders, smelting diamond powder gives XP, also copper, platinum and mercury but no others.

Some mod I have, Just Enough Items I think, lists how much Xp something gives when smelted. It lists nothing for all the things that are not giving XP, and small amounts for the rest except Rutile and Manganese which list a number of 45000002 XP

**Comment by dshadowwolf** [comment] 2017-09-07 16:42
Thanks for that information - it looks like we have an issue in the code somewhere that is causing the "getOreSmeltXP" function to not return a proper number, since Rutile and Manganese should not be that high.

According to the code, Rutile and Manganese should be giving 0.45  (with some level of error due to how PC's store floating-point numbers) per. Diamond Powder should give 0.15, if my memory is working. Copper, Platinum and Mercury should all have under 0.1 per (I think they're in the 0.04 to 0.07 range) and the rest should fall in the same range.

If they are not, then there is a logic error or similar happening in the code and I'm going to have to make a massively instrumented build to find this bug.

Many thanks for the report and the extra testing.

**Comment by dshadowwolf** [comment] 2018-05-01 17:47
Been looking at this for a while and have found the cause - the next release should have this issue fixed.

**Comment by dshadowwolf** [comment] 2018-05-02 16:16
Seems that the way furnace recipes are stored make it so you can't have two different recipes with related output (or even the same output) having different XP values. With that in mind... This is now fixed in -dev

**Closed as completed** 2018-10-18 18:31 UTC
Labels: Base Metals
